- name: Install mysql
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-client
    - mysql-server
    - python3-pymysql

- name: Check if mysql is started and enabled on boot
  service: "name=mysql state=started enabled=true"

- name: Create wordpress database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Create wordpress database user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Restart mysql
  ansible.builtin.shell:
    cmd: systemctl restart mysql
