- name: Install mysql
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - mysql
    - mysql-server
    - python3-PyMySQL

- name: Check if mysql is started and enabled on boot
  service: "name=mysqld state=started enabled=true"

- name: Create wordpress database
  community.mysql.mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Create wordpress database user
  community.mysql.mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present

- name: Restart mysql
  ansible.builtin.shell:
    cmd: systemctl restart mysqld
